name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  build-x64:
    runs-on: ubuntu-latest
    name: Build x64
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Make build script executable
      run: chmod +x build.sh
    
    - name: Run build script
      run: ./build.sh

  build-arm64:
    runs-on: ubuntu-latest
    name: Build ARM64
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup ARM64 cross-compilation environment
      run: |
        sudo dpkg --add-architecture arm64
        sudo apt-get update
        sudo apt-get install -y \
          crossbuild-essential-arm64 \
          g++-aarch64-linux-gnu \
          gcc-aarch64-linux-gnu
    
    - name: Make build script executable
      run: chmod +x build-arm64.sh
    
    - name: Run ARM64 build script
      run: ./build-arm64.sh